# Generated by Django 3.0.4 on 2020-03-29 16:43

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='', max_length=100, verbose_name='Student Name')),
                ('phone_number', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Phone number must be of the form: 9876543210.', regex='^[0-9]{10}$')], verbose_name='Phone Number')),
                ('batch_number', models.IntegerField(default=0, verbose_name='Batch number')),
                ('password', models.CharField(max_length=30, verbose_name='Password')),
                ('no_of_class_attended', models.IntegerField(default=0)),
                ('last_class_attended', models.DateTimeField(auto_now_add=True)),
                ('last_fees_paid', models.DateTimeField(default=datetime.datetime(1969, 12, 31, 18, 7, tzinfo=utc))),
                ('validated', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_logged_in', models.BooleanField(default=False, verbose_name='Logged in status')),
                ('unseen_message_count', models.IntegerField(default=0)),
                ('unseen_file_count', models.IntegerField(default=0)),
                ('email_address', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('fileName', models.CharField(default='temp.txt', max_length=1000)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('allowedUsers', models.ManyToManyField(to='Registry.UserData')),
            ],
            options={
                'ordering': ('-upload_time', 'fileName'),
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=3000, verbose_name='Message: ')),
                ('datePosted', models.DateTimeField(default=datetime.datetime(1969, 12, 31, 18, 7, tzinfo=utc), verbose_name='Date Posted: ')),
                ('allowedUsers', models.CharField(max_length=1000, verbose_name='Allowed Users: ')),
                ('sender', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='Registry.UserData')),
            ],
            options={
                'ordering': ('-datePosted',),
            },
        ),
    ]
