# Generated by Django 3.0.4 on 2020-03-29 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registry', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='allowedUsers',
        ),
        migrations.AddField(
            model_name='message',
            name='allowedUsers',
            field=models.ManyToManyField(related_name='allowed_viewers', to='Registry.UserData'),
        ),
    ]
