# Generated by Django 2.2.1 on 2019-06-03 07:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storedata',
            name='last_class_attended',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
