# Generated by Django 2.2.1 on 2019-06-03 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registry', '0002_storedata_last_class_attended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storedata',
            name='last_class_attended',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
