# Generated by Django 2.2.1 on 2019-06-03 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registry', '0003_auto_20190603_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storedata',
            name='last_class_attended',
            field=models.DateField(auto_now_add=True),
        ),
    ]
