# Generated by Django 2.2.1 on 2019-06-05 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registry', '0007_auto_20190603_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='storedata',
            name='mac_address',
            field=models.BigIntegerField(default=0),
        ),
    ]
