# Generated by Django 2.2.1 on 2019-06-07 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registry', '0009_fileupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.CharField(default='admin', max_length=100, verbose_name='Sender: '),
        ),
    ]
