# Generated by Django 2.2.1 on 2019-06-08 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registry', '0011_auto_20190608_1317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileupload',
            old_name='files',
            new_name='uploadedFile',
        ),
    ]
