# Generated by Django 2.2.1 on 2019-06-15 09:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registry', '0015_auto_20190613_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='datePosted',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 15, 14, 42, 44, 737670), verbose_name='Date Posted: '),
        ),
    ]
