# Generated by Django 2.2.1 on 2019-06-15 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registry', '0020_auto_20190615_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storedata',
            name='last_class_attended',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
