# Generated by Django 2.2.1 on 2019-06-17 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registry', '0021_auto_20190615_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='storedata',
            name='email_address',
            field=models.EmailField(default=None, max_length=254),
        ),
    ]
