# Generated by Django 2.2.1 on 2019-06-17 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registry', '0023_auto_20190617_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storedata',
            name='email_address',
            field=models.EmailField(max_length=254),
        ),
    ]
