# Generated by Django 3.0.4 on 2020-03-27 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registry', '0024_auto_20190617_1128'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fileupload',
            options={'ordering': ('-upload_time',)},
        ),
    ]
